#!/usr/bin/env node
/**
 * Seed data generator for Surbias.
 *
 * Reads scripts/seed/stories.json (30 stories, each with 5 translations) and
 * emits scripts/seed/seed.sql with one post per (story, locale) pair plus a
 * realistic reaction distribution. All seeded rows carry is_seed=1 so they can
 * be wiped in one DELETE later.
 *
 * Run:  node scripts/seed/generate.mjs
 * Apply remote:  npx wrangler d1 execute surbias-db --file=scripts/seed/seed.sql --remote
 * Purge remote:  npx wrangler d1 execute surbias-db --remote --command "DELETE FROM posts WHERE is_seed = 1"
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const STORIES_PATH = join(__dirname, 'stories.json');
const OUT_PATH = join(__dirname, 'seed.sql');

const LOCALES = ['en', 'es', 'pt', 'fr', 'de'];
const REACTION_TYPES = ['metoo', 'hug', 'strength', 'respect', 'solidarity'];

// Deterministic PRNG (mulberry32) — same seed → same output, so re-running
// the generator does not churn the SQL diff unless content changes.
function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const rand = mulberry32(20260425);
const randInt = (min, max) => Math.floor(rand() * (max - min + 1)) + min;
const pick = (arr) => arr[Math.floor(rand() * arr.length)];

// Short alphanumeric ID generator (mimics nanoid shape, deterministic).
const ALPHABET = '0123456789abcdefghijklmnopqrstuvwxyz';
function shortId(prefix = '', len = 12) {
  let s = '';
  for (let i = 0; i < len; i++) s += ALPHABET[Math.floor(rand() * ALPHABET.length)];
  return prefix + s;
}

function slugify(title) {
  return title
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .slice(0, 60)
    .replace(/-$/, '');
}

function sqlStr(s) {
  return `'${String(s).replace(/'/g, "''")}'`;
}

// Reaction distribution buckets — Pareto-ish so the feed has variety.
//   bucket weight (% of posts), [min,max] total reactions
const REACTION_BUCKETS = [
  { weight: 0.30, range: [0, 2] },   // long tail
  { weight: 0.40, range: [3, 10] },  // mid
  { weight: 0.20, range: [10, 30] }, // popular
  { weight: 0.10, range: [30, 80] }, // viral
];

function pickReactionTotal() {
  const r = rand();
  let acc = 0;
  for (const b of REACTION_BUCKETS) {
    acc += b.weight;
    if (r <= acc) return randInt(b.range[0], b.range[1]);
  }
  return 0;
}

// Distribute total reactions across the 5 reaction types — biased toward
// metoo/hug (more empathy-oriented), but always with some spread.
function splitReactions(total) {
  const counts = { metoo: 0, hug: 0, strength: 0, respect: 0, solidarity: 0 };
  const weights = { metoo: 0.32, hug: 0.26, strength: 0.16, respect: 0.14, solidarity: 0.12 };
  for (let i = 0; i < total; i++) {
    const r = rand();
    let acc = 0;
    for (const t of REACTION_TYPES) {
      acc += weights[t];
      if (r <= acc) { counts[t]++; break; }
    }
  }
  return counts;
}

// createdAt distribution — last 120 days, weighted toward the recent half so
// the feed feels alive but the "older" tail still exists.
function pickCreatedAt(now) {
  const maxDaysAgo = 120;
  // Square the random to bias toward small values (= recent).
  const daysAgo = Math.floor(Math.pow(rand(), 1.7) * maxDaysAgo);
  const secondsJitter = randInt(0, 86399);
  return Math.floor(now / 1000) - daysAgo * 86400 - secondsJitter;
}

function main() {
  const stories = JSON.parse(readFileSync(STORIES_PATH, 'utf8'));

  if (!Array.isArray(stories) || stories.length === 0) {
    console.error('stories.json is empty or not an array');
    process.exit(1);
  }

  const now = Date.now();
  const lines = [];
  lines.push('-- Surbias seed data — generated by scripts/seed/generate.mjs');
  lines.push('-- All rows have is_seed=1; purge with: DELETE FROM posts WHERE is_seed = 1;');
  lines.push('-- Reactions cascade-delete via posts FK.');
  lines.push('-- NOTE: no BEGIN/COMMIT — D1 wraps file execution in its own transaction and');
  lines.push('-- rejects raw SQL transaction statements (must use state.storage.transaction()).');
  lines.push('');

  let postCount = 0;
  let reactionCount = 0;

  for (const story of stories) {
    const { category, translations } = story;
    if (!category || !translations) continue;

    for (const locale of LOCALES) {
      const t = translations[locale];
      if (!t || !t.title || !t.body) continue;

      const postId = shortId('s', 11);
      const slug = slugify(t.title);
      const createdAt = pickCreatedAt(now);
      const total = pickReactionTotal();
      const counts = splitReactions(total);
      const reactionCountsJson = JSON.stringify(counts);

      lines.push(
        `INSERT INTO posts (id, user_id, slug, category, title, body, locale, is_anonymous, status, flag_count, reaction_counts, pinned, is_seed, created_at) VALUES (`
        + `${sqlStr(postId)}, NULL, ${sqlStr(slug)}, ${sqlStr(category)}, ${sqlStr(t.title)}, ${sqlStr(t.body)}, ${sqlStr(locale)}, 1, 'published', 0, ${sqlStr(reactionCountsJson)}, 0, 1, ${createdAt});`
      );
      postCount++;

      for (const [type, n] of Object.entries(counts)) {
        for (let i = 0; i < n; i++) {
          const reactionId = shortId('r', 11);
          // sessionHash carries a 'seed:' prefix; userId stays NULL. The
          // unique index on (post_id, session_hash) is per-post so the same
          // marker can repeat across posts but must be unique within a post,
          // hence we mint a fresh hash per reaction.
          const sessionHash = `seed:${shortId('', 10)}`;
          // Reaction timestamp: between post creation and now, biased toward
          // shortly after the post (typical engagement curve).
          const ageSeconds = Math.max(60, Math.floor(now / 1000) - createdAt);
          const offsetSeconds = Math.floor(Math.pow(rand(), 2) * ageSeconds);
          const reactCreatedAt = createdAt + offsetSeconds;
          lines.push(
            `INSERT INTO reactions (id, post_id, user_id, session_hash, type, created_at) VALUES (`
            + `${sqlStr(reactionId)}, ${sqlStr(postId)}, NULL, ${sqlStr(sessionHash)}, ${sqlStr(type)}, ${reactCreatedAt});`
          );
          reactionCount++;
        }
      }
    }
  }

  lines.push('');
  lines.push(`-- ${postCount} posts, ${reactionCount} reactions`);

  writeFileSync(OUT_PATH, lines.join('\n') + '\n');
  console.log(`Wrote ${OUT_PATH}: ${postCount} posts, ${reactionCount} reactions across ${LOCALES.length} locales.`);
}

main();
